# Settings specific to host prod-web7.cashmusic.org.

# Override default production environment label for bobo server.
site_profile::web::deployment_environment: production-bobo

# prod-web7 runs bobo, not the CASH Music platform, so override the default vhost.
site_profile::web::vhosts:
  platform_default:
    default_vhost: false
  bobo:
    port: 80
    default_vhost: true
    docroot: '/var/www/bobo'
    override:
      - 'All'
    docroot_owner: deploy
    docroot_group: deploy
    redirectmatch_status:
      - '404'
    redirectmatch_regexp:
      - '\.git(/.*|$)/'
    require:
      - User[deploy]

# This host needs an additional code deploy script for bobo.
site_profile::web::web_deploy_scripts:
  - 'bobo_code_deploy.sh'
  - 'bobo_code_deploy_with_sql.sh'
